### ISSUE TITLE
API 23 Camera: Error 100

### ISSUE THREAD

**Issue by EzequielAdrianM** [ragnraok/RxCamera#12]
The first time I access to camera, the permission request dialog is shown. But when I select "ALLOW".
The Camera gives:

E/Camera: Error 100

I have looked for Info about the error. But it is not a BUG that I can handle inside my application. Take a look at this issue: http://stackoverflow.com/questions/6837975/camera-error-100

**Comment by ragnraok** [comment]
It seem that there is something wrong for your camera parameters, can you post your code here?

**Comment by EzequielAdrianM** [comment]
Sorry, It is my fault and the thing is that I am currently testing my app on CyanogenMod 13. And it is a CM-related internal bug. Your code is fine. Thankyou!
