### ISSUE TITLE
Suggest update RxJava and RxAndroid version.

### ISSUE THREAD

**Issue by wind0ws** [ragnraok/RxCamera#16]
I see your lib use old version of rxjava and rxandroid.

And currently,I use your lib by this in gradle script:

```
compile 'io.reactivex:rxjava:1.1.1'
 compile 'io.reactivex:rxandroid:1.1.0'

    compile('com.ragnarok.rxcamera:lib:0.0.2'){
        exclude group: 'io.reactivex',module:'rxjava'
        exclude group: 'io.reactivex',module:'rxandroid'
    }
```

**Comment by wind0ws** [comment]
By the way,thanks to ragnraok for your awesome RxCamera Lib.

**Comment by sibelius** [comment]
@wind0ws would you mind to send a PR for this?

**Comment by wind0ws** [comment]
@sibeliusseraphini Sorry for my poor english.Does PR means Public-Relation?
  RxCamera depend on RxAndroid and RxJaAVA, RxAndroid depend on RxJava.

**Comment by sibelius** [comment]
PR - Pull Request
