### ISSUE TITLE
Multiple Image at a time using rxcamera

### ISSUE THREAD

**Issue by AanalShah** [ragnraok/RxCamera#30]
Hey can i take multiple image before close the camera at a time ?

how to make brust mode using rxcamera 
pls help me

**Comment by ragnraok** [comment]
what do you mean of "brust mode"?

**Comment by AanalShah** [comment]
its means u can take a batch of image without closing camera in one time

**Comment by ragnraok** [comment]
That is impossible, the system [takePicture](https://developer.android.com/reference/android/hardware/Camera.html#takePicture%28android.hardware.Camera.ShutterCallback, android.hardware.Camera.PictureCallback, android.hardware.Camera.PictureCallback, android.hardware.Camera.PictureCallback%29) call will definitely stop your preview, or you can use `oneShotRequest`, but you need to convert the yuv to rgb manually

**Comment by AanalShah** [comment]
okk
