### ISSUE TITLE
Could you please release a new version

### ISSUE THREAD

**Issue by afaucogney** [ragnraok/RxCamera#38]
Latest publish version is 0.0.4 and do not yet support latest feature (Builder)
Latest commit doesn't build on Jitpackio https://jitpack.io/#ragnraok/RxCamera

**Comment by ragnraok** [comment]
do you mean the `RxCameraActionBuilder`?

and I didn't publish this library on jitpack, please use jcenter

**Comment by afaucogney** [comment]
RxCameraConfig config = new RxCameraConfig.Builder()
                .useBackCamera()
                .setAutoFocus(true)
                .setPreferPreviewFrameRate(15, 30)
                .setPreferPreviewSize(new Point(640, 480), false)
                .setHandleSurfaceEvent(true)
                .build();

Is not available with the 0.0.4 version

Jitpack just allow to use any version of the lib available on github, even version derived from commit. It is usefull in your case, but as it doesn"t work, I had to put a module with your lib i my app project (it less easy to update)

**Comment by ragnraok** [comment]
ok, I will release the new version after some necessary bugs fixed
