### ISSUE TITLE
Adjust capture resolution

### ISSUE THREAD

**Issue by ghost** [ragnraok/RxCamera#4]
Is there a way to adjust the capture resolution instead of just the preview size?

**Comment by ragnraok** [comment]
the current version doesn't have directly interface to set the picture size, so you should get native camera object by `RxCamera.getNativeCamera` and set the picture size by called [setPictureSize](http://developer.android.com/intl/zh-cn/reference/android/hardware/Camera.Parameters.html) in `Camera.Parameters`
