### ISSUE TITLE
Question about rotate the preview byte[] cameraData?

### ISSUE THREAD

**Issue by keepfit** [ragnraok/RxCamera#44]
Hi: 

rotateMatrix - this matrix help you rotate the camera data in portrait 

Would you explain it to me why the preview byte[] cameraData has been rotated in portrait?

Many thanks!

**Comment by ragnraok** [comment]
each camera in android devices has its specific install angle，and mostly can retrieve from `CameraInfo.orientation`, thats why we need to call `setDisplayOrientation`, but the return camera data in `onPreviewFrame` still not rotated, so you will need this `rotateMatrix`
