### ISSUE TITLE
Capture image with Aspect Ratio 4:3

### ISSUE THREAD

**Issue by bunhann** [ragnraok/RxCamera#48]
Hi, 
I want to take a photo with aspect ratio 4:3. Currently, some device it capture with 4:3 and some with 16:9, so i have problem while scale image which were captured.

Sorry for my bad English. Hope i can get some advice soon.

**Comment by ragnraok** [comment]
Can you post a screenshot? And what's the picture size passed to the `TakePictureRequest` ?

**Comment by nonameden** [comment]
Hi there,

Awesome library, found an issue in the **TakePictureRequest** class in function **findClosetPictureSize**
`int diff = Math.abs(size.width - width) + Math.abs(size.height);`

height never been used, so I believe it should be:
`int diff = Math.abs(size.width - width) + Math.abs(size.height - height);`

Regards, d

**Comment by ragnraok** [comment]
@nonameden you are right, I will fix this

**Comment by nonameden** [comment]
Thank you,

Do you have in plans add support for Camera2?

**Comment by bunhann** [comment]
Thank you so much.

**Comment by ragnraok** [comment]
@nonameden Not yet, but may be I will release a new called RxCamera2 to support the camera2 API

**Comment by uDevel** [comment]
Is this push to com.ragnarok.rxcamera:lib:0.0.5?
It's in master but not 0.05.
