### ISSUE TITLE
Front Camera Touch Focus

### ISSUE THREAD

**Issue by ezesolares** [ragnraok/RxCamera#49]
Hello, great libraries.

I was wondering if there is a reason why you cant use touch focus while using the front facing camera, it doesnt work on the example app.
Im testing it on my nexus 6p.

I keep getting area focus and metering failed..

Thanks in advance

**Comment by ragnraok** [comment]
It is the `onError` get called? may be the front camera on nexus 6p does not support area focus and metering, can you post your code here?

**Comment by ezesolares** [comment]
Im using the example to test, nothing else. Also, the nexus 6p support touch focus on their own camera app.

The error im getting is 
 D/Example.MainActivity: area focus and metering failed: null

which comes from the areaFocusAction in RxCameraActionBuilder.java
and from the 
if (parameters.getMaxNumFocusAreas() < focusAreaList.size()) {
for which getMaxNum is 0 and focusArea is 1

The Nexus 6p has touch focus on their own camera app and i also have the same problem with my other test device (Galaxy S5 with Android 5.0), but as i said, only fails on the front camera, it works great on the back camera on both devices.

I dont know where to check if the nexus 6p support area focus and metering using camera 1 api, but it seems that does support it on the camera 2 api.

i added this check on areasfocus, just to see the focusmode while touching

List<String> focusModes1 = parameters.getSupportedFocusModes();
for(String tt: focusModes1)
    Log.d(TAG, "focus modesf: " + tt);

and its says only support fixed.. so im guessing focus on front camera only works using camera 2 api

Thanks in advance

**Comment by ragnraok** [comment]
It means that area focus not support for the front camera, at least in camera1 API, for these devices, may be have a better area focus implementation under the camera2 API, so, for the RxCamera, you can't use area focus for these devices' front camera

May be I will develop a new library for the camera2 API...
