### ISSUE TITLE
RxCamera.CameraInternal: open camera failed: Fail to connect to camera service

### ISSUE THREAD

**Issue by spirosoik** [ragnraok/RxCamera#5]
I ran the example and the camera cannot open in a samsung lg tab g pad 7.0 with 5.0.1. Same problem for Nexus 5 with 6.0.1

**Comment by ragnraok** [comment]
did you add `<uses-permission android:name="android.permission.CAMERA" />` in your AndroidManifest.xml?

**Comment by spirosoik** [comment]
Hi @ragnraok I found the problem I think. My case is to open the camera when the screen is visible not with a button open. I understood that the problem is that surface is not available so I added the listener for `TextureView`. When the listener says that I am available then I open the camera without a problem. Just I suggest to add this case in your README or your internal surface listener is not work properly. 

By the way great job thanks for the great repo. You can close the issue

**Comment by ragnraok** [comment]
RxCamera will add a internal surface callback if you set `HandleSurfaceEvent` to true, and will call `startPreview` when the surface is available, but the `camera.open` can be called at any time whether the surface is available, may be the internal logic of open camera has something wrong, I will check that, thanks!

**Comment by spirosoik** [comment]
@ragnraok Yes I know but something is not working properly I suppose.

**Comment by sibelius** [comment]
@spirosoik could you provide your solution?

**Comment by sibelius** [comment]
@ragnraok do you have an example without an open button?

**Comment by samy-baili** [comment]
Anyone find a solution for this issue ?
