### ISSUE TITLE
Tag release

### ISSUE THREAD

**Issue by uDevel** [ragnraok/RxCamera#50]
Can you please tag the 0.0.5 release in github?
Contributor and consumer can then know which code is in release, and which is not.

For example, does 0.0.5 have all the code in master branch?

Thanks.

**Comment by ragnraok** [comment]
the 0.0.5 is almost the newest version, you can directly use this

**Comment by uDevel** [comment]
It seems it doesn't have the take picture height bugfix.
[https://github.com/ragnraok/RxCamera/issues/48](url)
