### ISSUE TITLE
Fail to take picture with dual back camera on Android 7

### ISSUE THREAD

**Issue by lucas34** [ragnraok/RxCamera#53]
Hi,

I'm having this issue :  takePicture failed, error=-38 (ENOSYS). This issue seems to happen only on Android 7. 

Cannot reproduce this with the emulator. 

I have this issue on a dual back camera phone.

Any idea ?

**Comment by ragnraok** [comment]
did you grant the permission of Camera? and please post you code here

**Comment by lucas34** [comment]
Yes I did grant the permission,

However, I often have this issue but cannot find a correct pattern to reproduce the issue. I think some of the camera app on the phone is not releasing the camera.
