### ISSUE TITLE
Error Please Hep me

### ISSUE THREAD

**Issue by mahirekici** [ragnraok/RxCamera#55]
Hi  

I have the app_name parameter in the manifest file of this project. I'm getting an error

Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@label value=(UfeedBackMe) from AndroidManifest.xml:26:9-36
  	is also present at [com.ragnarok.rxcamera:lib:0.0.5] AndroidManifest.xml:11:18-50 value=(@string/app_name).
  	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:22:5-87:19 to override.

**Comment by ragnraok** [comment]
It seem that it has multiple definitions of ``app_name``, try to rename you string name, I will fix it later
