### ISSUE TITLE
Captured Image is saved with wrong orientation (After Switching Camera - Moto G4 Plus)

### ISSUE THREAD

**Issue by amarilindra** [ragnraok/RxCamera#56]
Hai, 

By default i'm opening front camera and it is saving properly but when I switch camera to back it is saving with wrong orientation. 

Now I changed config to open back camera first and it saves fine but issue starts with front camera.

In short, image is saved properly only for camera specified in config. 

Device: Moto G4 Plus

Any idea?
Thanks

**Comment by ragnraok** [comment]
that may be the`` takepicture`` api implemented has some problem, can you check-out the exif info the output jpg?
